package dev.willtda.simpleschematics.printing;

import net.minecraft.SharedConstants;
import net.minecraft.commands.arguments.selector.options.EntitySelectorOptions;
import net.minecraft.core.cauldron.CauldronInteraction;
import net.minecraft.core.dispenser.DispenseItemBehavior;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.server.Bootstrap;
import net.minecraft.world.entity.EntityType;
import net.minecraft.world.item.CreativeModeTabs;
import net.minecraft.world.item.alchemy.PotionBrewing;
import net.minecraft.world.level.block.ComposterBlock;
import net.minecraft.world.level.block.FireBlock;
import net.minecraftforge.registries.GameData;

import java.lang.reflect.Field;

/**
 * Initialises the declared Minecraft/Forge version's registries for standalone checks.
 * Forge 47.4 additionally starts network channels in Bootstrap.bootStrap(). Those
 * channels require event constructors generated by ModLauncher. These tests cover
 * states, materials, transforms and NBT, so they initialise the real registry
 * sequence without starting networking. Packet handling and world interaction
 * require an in-game check and are outside this harness.
 */
final class PrintTestBootstrap {
    private PrintTestBootstrap() {
    }

    static void initialise() {
        SharedConstants.tryDetectVersion();
        try {
            Field bootstrapped = Bootstrap.class.getDeclaredField("isBootstrapped");
            bootstrapped.setAccessible(true);
            if (bootstrapped.getBoolean(null)) return;
            // Registry construction checks this flag, just as in the vanilla bootstrap.
            bootstrapped.setBoolean(null, true);
        } catch (ReflectiveOperationException exception) {
            throw new IllegalStateException("Cannot initialise Minecraft test registries", exception);
        }
        if (BuiltInRegistries.REGISTRY.keySet().isEmpty()) {
            throw new IllegalStateException("Unable to load registries");
        }
        FireBlock.bootStrap();
        ComposterBlock.bootStrap();
        if (EntityType.getKey(EntityType.PLAYER) == null) {
            throw new IllegalStateException("Failed loading EntityTypes");
        }
        PotionBrewing.bootStrap();
        EntitySelectorOptions.bootStrap();
        DispenseItemBehavior.bootStrap();
        CauldronInteraction.bootStrap();
        BuiltInRegistries.bootStrap();
        CreativeModeTabs.validate();
        GameData.vanillaSnapshot();
    }
}